// Each new term in the FIbonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//  1, 2, 3, 5, 8, 13, 21, 34, 55, 89
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-values terms

function fibonnaci() {
    let terms = 0
    let sum = [1, 2]
    for (let i = 0; i < sum.length; i++) {
        let newAdd = sum[sum.length-1] + sum[sum.length-2]
        if (newAdd >= 4000000) {
            break
        } else {
            sum.push(newAdd)
        }
    }
    sum.forEach((num) => {
        if (num % 2 === 0) {
            terms += num
        }
    })
    return terms
}

console.log(fibonnaci())